name: 'publish'

on:
  push:
    branches:
      - 'dev'
      - 'main'
    tags:
      - '*'

jobs:  
  build:
    name: 'Build and publish'
    runs-on: ubuntu-latest
    steps:
    
      - name: 'Build checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/pixilib/gaelo-flow-backend
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            latest
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to github registery
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 'salimkanoun'
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: 'Install and Build'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: setup git config
        run: |
          git config user.name "Salim Kanoun"
          git config user.email "salim.kanoun@gmail.com"
          
      - run: |
          echo '//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
                              @pixilib:registry=https://npm.pkg.github.com
                              always-auth=true' > ${{ github.workspace }}/.npmrc
          cat .npmrc
          
      - run: yarn install --frozen-lockfile
        working-directory: ./GaelO-Flow
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'set version'
        if: github.ref_type == 'tag'
        run: yarn version --new-version ${{ github.ref_name }}

      - run : yarn build
        working-directory: ./GaelO-Flow

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
