name: 'build swagger'

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:  
  swagger:
    name: 'Swagger build and publish'
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            # Opens tcp port 6379 on the host and service container
            - 6379:6379
      orthanc:
        image: osimis/orthanc:23.4.0
        ports: 
          - 8042:8042
      postgres:
        image: postgres:13.1
        env:
            POSTGRES_DB: "gaelo-flow"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
        ports: 
            - 5432:5432
    steps:
      
      - name: 'Build checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: 'Install and Build'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - run: yarn install --frozen-lockfile
        working-directory: ./GaelO-Flow

      - run : yarn build-api-docs
        working-directory: ./GaelO-Flow

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
permissions:
  contents: read
  packages: write