name: 'unit test'

on:
  push:
    branches:
      - '*'

jobs:  
  test:
    name: 'Run unit test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Build checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: 'Install and Build'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          
      - run: yarn install --frozen-lockfile
        working-directory: ./GaelO-Flow

      - run : yarn test
        working-directory: ./GaelO-Flow
